export const SHOW_LOADING = 'SHOW_LOADING'

export const HIDE_LOADING = "HIDE_LOADING"

export const ACTION_LOCAL_WEATHER = "ACTION_LOCAL_WEATHER"

export const ACTION_CITY_WEATHER = "ACTION_CITY_WEATHER"

export const SET_AIR_POLLITION = "SET_AIR_POLLITION"

export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER"

export const SET_ONE_CALL = "SET_ONE_CALL"

export const POPUP_ALERT_VISIBILITY = "POPUP_ALERT_VISIBILITY"

export const POPUP_ALERT_HIDDEN = "POPUP_ALERT_HIDDEN"